from typing import Union

import pytest

from puzzle_solver.model import PuzzlePiece, Edge, Point

# Test cases generated by placing points in Geogebra and reading the intersection point


def check_middle_point(
    corners: list[Point], expected_x: Union[float, int], expected_y: Union[float, int]
):
    edges = [
        Edge([corners[i], corners[(i + 1) % len(corners)]], str(i), piece_id="p11")
        for i in range(len(corners))
    ]
    puzzle_piece = PuzzlePiece(edges=edges, id="1", vertices=[])
    puzzle_piece.rotate_point_lists()
    new_point = puzzle_piece.get_middle_point()

    assert new_point.x == (
        expected_x if type(expected_x) is int else pytest.approx(expected_x)
    )
    assert new_point.y == (
        expected_y if type(expected_y) is int else pytest.approx(expected_y)
    )


def test_get_middle_point_1():
    check_middle_point([Point(1, 2), Point(2, 1), Point(3, 2), Point(2, 3)], 2, 2)


def test_get_middle_point_2():
    check_middle_point([Point(1, 3), Point(1, 1), Point(4, 1), Point(4, 3)], 2.5, 2)


def test_get_middle_point_3():
    check_middle_point([Point(2, 3), Point(1, 1), Point(4, 1), Point(4, 3)], 2.8, 2.2)


def test_get_middle_point_4():
    check_middle_point(
        [Point(0.9609, 1.13025), Point(1, 1), Point(4.04772, 2.8472), Point(4, 3)],
        2.3762093391605332,
        1.9174728927736888,
    )
